### ISSUE TITLE
suggestion for parameters

### ISSUE THREAD

**Issue by ashkank83** [slorber/react-async-hook#1]
If you want to pass all params to the async Function (not in array form), does it make sense to change line 78 to 
```js
const promise = asyncFunction(...params);
```

**Comment by slorber** [comment]
Hi, and sorry for the delay

Yes it makes sense to me. Actually I'm not even sure to understand anymore why my example is working :O (as I pass a [id] array to the fetch method which expect an "id" non array param.

I don't have much time to work on this currently but would gladly accept PRs or give commit permissions for external contributors

**Comment by slorber** [comment]
Can confirm the bug. Will probably solve it soon + convert this project to TS

**Comment by slorber** [comment]
@ashkank83 @abeauvois the project is now converted to TS and has this bug fixed

Just released an alpha in case I want to do changes but the code almost did not chance: `^2.0.0-alpha.1`
