### ISSUE TITLE
Async request runs twice when using useAsync with executeOnMount set to true

### ISSUE THREAD

**Issue by cruiserkernan** [slorber/react-async-hook#13]
I'm trying out this package and noticed that the useAsync hook runs my fetch request twice.
I looked at the the implementation and found these lines of code which I don't understand.
Why is executeAsyncOperation run twice? 
```typescript
const isMounting = !isMounted();
  useEffect(() => {
    if (isMounting) {
      normalizedOptions.executeOnMount && executeAsyncOperation(...params);
      normalizedOptions.executeOnMount && executeAsyncOperation(...params);
    } else {
      normalizedOptions.executeOnUpdate && executeAsyncOperation(...params);
    }
  }, params);
```

**Comment by slorber** [comment]
ah thanks :O 

My last commit had a typo :O sorry will fix that later today

https://github.com/slorber/react-async-hook/commit/501f53891dc9213baba61ad50dbf651dbf340eb2#diff-f41e9d04a45c83f3b6f6e630f10117feR246

**Comment by slorber** [comment]
3.5.3
