### ISSUE TITLE
Execute on condition

### ISSUE THREAD

**Issue by ed-sparkes** [slorber/react-async-hook#2]
Hi is there a way to execute on condition ? 

My  use case is that i wait for an async task to retrieve an access token before i then call my api. 

The result of the token call is passed as dependency to the second one but it still has an initial value and as such the api call is called pointlessly an extra time with no access token

Thanks, Ed

**Comment by slorber** [comment]
Hi

You can use a closure and do a if inside it to return nothing if the token
is not here. There's a search input example where the search is not done
when input is empty, this is almost the samr




Le ven. 5 juil. 2019 à 16:11, Ed Sparkes <notifications@github.com> a
écrit :
