### ISSUE TITLE
get error code from "error"

### ISSUE THREAD

**Issue by EkaterinaMozheiko** [slorber/react-async-hook#20]
Hi,

is there any way to get an error code from error variable (result of useAsync hook)? It seems that the only way to do it is to parse message string. I think it should be the "code" property in Error type (along with "name" and "message" whish exist already)

Thanks

**Comment by slorber** [comment]
Hi

You mean http code?

If yes ymi can't do anything for you this lib is not coupled to http
particularly and can work with any async system. I just expose the error
the same way it is thrown by the async fn

If you throw an error with code, there will be a code. If you use axios,
error.reponse.status or something similar should be provided by axios,
etc...

**Comment by EkaterinaMozheiko** [comment]
Ok, thanks!

**Comment by nunos7** [comment]
Hi, it's possible to show one example using axios and return de status code?
I'm new working with react and i don't figure it out how to get the status code :(

Thanks,
NS
