### ISSUE TITLE
Mechanism to refresh value without loading state

### ISSUE THREAD

**Issue by fabiosantoscode** [slorber/react-async-hook#25]
Consider this (incomplete) example, where we fetch some data when the component mounts, and we keep refreshing it every few minutes:

```
function MyComponent() {
  const fetchDataResult = useAsync(fetchTheData, [])
  useEffect(() => {
    setInterval(() => {
      fetchDataResult.execute()
    }, pollInterval)
  }, [])

  // ... show loading, error, or result to the user.
}
```

This works just fine, but it has a problem. Whenever we call `.execute()`, `.loading` will become true for a moment while the data is in-transit, temporarily showing the loading screen. If the fetch failed (perhaps because the user lost network connectivity), the error screen is displayed.

I would like to refresh while keeping the on-screen data on-screen. In case of failure, I would like for my code to simply try again later at the next refresh time.

Should there be a mechanism to refresh data without going through loading states, and potentially even ditching error state?

I have considered this workaround, and multiple variations of it:

```
const initialFetchDataResult = useAsync(fetchTheData, [])
const reFetchDataResult = useAsync(fetchTheData, [])

const activeFetch = reFetchDataResult.status === 'success' ? reFetchDataResult : initialFetchDataResult
```

**Comment by slorber** [comment]
Hi

Normally there's a setLoading option that you can use to define the state update you want when a request is made.

I thought it was documented but it seems not, will add it soon

**Comment by fabiosantoscode** [comment]
That sounds nice. Thanks for pointing it out. I shall dig into the source code :)

**Comment by slorber** [comment]
Ah actually it's documented here:

https://github.com/slorber/react-async-hook#how-can-i-keep-previous-results-available-while-a-new-request-is-pending

Definitively need to improve the doc though :)
