### ISSUE TITLE
BUG - useAsync requires params array or endless loops

### ISSUE THREAD

**Issue by baebb** [slorber/react-async-hook#27]
I'm using useAsync like follows:
```
const { loading, result } = useAsync(getBalancesDemoData);
```
`getBalancesDemoData` returns a promise:
```
export const getBalancesDemoData = (query) => {
  console.log('hit me');
  // console.log("parameters sent to API", query);
  return new Promise((resolve, reject) =>  {
    setTimeout(() => {
      resolve(balances);
      // reject('Bad');
    }, 1000);
  });
};
```
The hook stays in loading state and endlessly calls the function, as shown:
<img width="514" alt="image" src="https://user-images.githubusercontent.com/8374514/84116516-f3b1ea00-aa6a-11ea-8ed0-beda69daf518.png">

Passing an empty array to useAsync seems to solve things but feels bad.
```
const { loading, result } = useAsync(getBalancesDemoData, []);
```

**Comment by slorber** [comment]
```
const { loading, result } = useAsync(getBalancesDemoData);
```

You have to pass a dependency array, the 2nd arg is not optional (if you used TS you would see an error)
https://github.com/slorber/react-async-hook/blob/master/src/index.ts#L305

```
const { loading, result } = useAsync(getBalancesDemoData,[query]);
```

**Comment by slorber** [comment]
Eventually I could add a warning to the lib in case the deps array is missing, so that non-TS users know that they don't use the lib correctly

**Comment by baebb** [comment]
Yes please :)

**Comment by dan-lee** [comment]
I also recommend adding `useAsync` to the lint rule [`react-hooks/exhaustive-deps`](https://github.com/facebook/react/blob/master/packages/eslint-plugin-react-hooks/README.md#advanced-configuration) of `eslint-plugin-react-hooks`:

```ts
// .eslintrc.json
module.exports = {
  // ...
  rules: {
    'react-hooks/rules-of-hooks': 'error',
    'react-hooks/exhaustive-deps': [
      'error',
      {
        additionalHooks: '(useAsync|useAsyncCallback)',
      },
    ],
  }
}
```
