### ISSUE TITLE
typescript: describing type of error

### ISSUE THREAD

**Issue by vtaits** [slorber/react-async-hook#28]
I'm using `react-async-hook` with `axios`.

```typescript
const MyComponent: FC = () => {
  const asyncResult = useAsync<ResultType>(
    async () => {
      const response = await axios.get(`/api/endpoint/`);

      return response.data;
    },

    [],
  );

  if (asyncResult.error) {
    // do anything with error of axios
    console.error(asyncResult.error.response);
  }
};
```

`typescript` throws error: `Property 'response' does not exist on type 'Error'`.

I want something like:

```
useAsync<ResultType, [], AxiosError>(...)
```

**Comment by slorber** [comment]
Hi,

Axios returns regular promises, and it's not possible to give the type of the error in a promise (there's no `Promise<R,E>`)

+, you can't even be sure that an error unrelated to Axios could be thrown in your async code, so it wouldn't be safe.

You should implement your own axios errorr typeguard, like

```
interface AxiosError<T = any> extends Error {
  config: {};
  code?: string;
  request?: any;
  response?: {};
  isAxiosError: boolean;
  toJSON: () => object;
}

const isAxiosError = (error: Error): error is AxiosError => !!(error as any).isAxiosError

const error = new Error("test");

if (isAxiosError(error)) {
  console.log(error.response);
}

console.log(error.response);
```

https://www.typescriptlang.org/play/?ssl=19&ssc=1&pln=1&pc=1#code/JYOwLgpgTgZghgYwgAgIIA9gHsDOBRKKLKAHgBVkBeZOEATwD5kJ1IQATHZAoqZAbwBQyZAiwgYwAOYAuAQF8A3MNFZ2EAPxycYKKCnKRUCAEcArhB1aa9Q8mM4ADuJya5-JSuA4M2fIWI5ACMsLAAbCFo7MCwAKQBlAHkAOTkACgBKKiYsIIArCAQwZXlBQTEQHWRvX1weYipkNOheOXqoDLkWhu80TDqAvkomAEIR5sGaLlo6DIA6Gv7-XjKKqu6h5BAIAHduQbSAIkgdQ4zlQWAYJsW-doneDKyhETXwiDmwrCkH4jmHZyVCDnQSlcoud6fb6-KD-SyA1wgoA


And then just use this typeguard


```
  if (asyncResult.error && isAxiosError(asyncResult.error)) {
    // do anything with error of axios
    console.error(asyncResult.error.response);
  }
```

but remember that you might have non-axios errors to handle as well!

(I thought isAxiosError was a fn included in Axios, but can't find it anymore)
