### ISSUE TITLE
BUG - passing in array params to useAsync results in an infinite loop/endless calling

### ISSUE THREAD

**Issue by MannanK** [slorber/react-async-hook#31]
I saw a recent issue that I think is related to this bug I'm facing (#27), but essentially what's happening is that I need to pass in two arrays into `useAsync()`, both of which contain parameters that will be parsed and forwarded to the api call I want to make. However, whenever I try to pass in arrays, I get stuck in an infinite loop where `useAsync()` just keeps executing. What's weirder is that I printed out the result of the api call inside my asynchronous function, and my fetch goes just fine. However, as soon as I return to the file with the `useAsync()` call, the results are `undefined`.

1. Here is the file where I call `useAsync()`. `getPostCollectionsBySlugs` is the async method and is shown in the next screenshot: this function takes in the parameters and parses them to make the queries, and then returns the awaited promise of the `fetch`. I tried passing in the params as two different arrays and as one array of objects, but both result in infinite loops.

![Screen Shot 2020-07-22 at 3 59 09 PM](https://user-images.githubusercontent.com/9904709/88223381-5f27d380-cc35-11ea-886c-e03899bd71a3.png)

2. Here's `getPostCollectionsBySlugs` which takes in the params.
![Screen Shot 2020-07-22 at 3 57 31 PM](https://user-images.githubusercontent.com/9904709/88223444-82528300-cc35-11ea-9eda-3289f600b02d.png)

3. Here's the infinite loop in my console when I print out the `posts` result after `useAsync()` returns. I don't have a screenshot but printing these same results inside `getPostCollectionsBySlugs` would give me the correct results from the api call.
![Screen Shot 2020-07-22 at 3 59 51 PM](https://user-images.githubusercontent.com/9904709/88230134-d5313800-cc3f-11ea-9907-61c932052e8c.png)

Everything's condensed for brevity, but the logic and idea is the same.

If I pass only two strings inside the array, and not arrays themselves as parameters, everything works fine. But it looks like as soon as I try to pass an array(s) as params, things break. Any help would be appreciated! Thanks.

**Comment by slorber** [comment]
Hey,


useAsync deps array is like useEffect deps, you have to pass it stable dependencies to ensure it does not re-execute nor create an infinite loop

This will create an infinite loop:


```
useAsync(doSomethingAsync,[{slug: "slug"1])
```

While this will not:

```
useAsync(doSomethingAsync,["slug"])
```

And this will not either:

```
const firstParam = useMemo(() => ({slug: "slug1"}),[])
useAsync(doSomethingAsync,[firstParam])
```

Unfortunately it's how hooks deps array work, this lib does not change anything to that, so it's the exact same behavior as the one of useEffect

**Comment by slorber** [comment]
searching for useEffect + infinite loop on google will bring you a lot of results to explain this better than me.

Some has even created libs to avoid this problem: https://github.com/kentcdodds/stop-runaway-react-effects

**Comment by MannanK** [comment]
@slorber Got it, I'll look into that more. Thanks!
