### ISSUE TITLE
Declarative way to update my list

### ISSUE THREAD

**Issue by pxd3v** [slorber/react-async-hook#37]
So im really enjoying applying react-async-hook i'm my app lists but im strugling with refreshing those lists when we delete an item or create/update an existing one. I'm currently imperative calling the .execute() in each function that mutates the items array but i would like to know an declarative way to do it, do u guys suport this feature? I feel like im wrongly using this. There is an example component: 

```
const Componente: React.FC = () => {
  const loadProfiles = useAsync(getProfiles, []);

  const handleDelete = async (id: number) => {
    await deleteProfile(id)
      .then(async (response) => {

        loadProfiles.execute();

      })
  };

  const asyncHandleDelete = useAsyncCallback(handleDelete);

return (
 ...list with the items and a delete button
)}
```

**Comment by itsmelion** [comment]
Perceptive question. 🤔
This is how i often use it too.

**Comment by slorber** [comment]
Hey.
I'll try to improve the documentation soon but if you use TS you should find methods like set/merge/setResult on loadProfiles. This way you can update the fetched value without refetching.

I don't know if it's possible to do such thing déclaratively, Apollo etc also do it imperatively afaik. For exemple when you create a Todo, we can't know for you if you want to append or prepend it to the Todo list

**Comment by pxd3v** [comment]
Hi guys!
The problem here isn't exactly the imperative way, i just didn't knew if i was using the hooks the right way hahaha is that how it is supposed to be?
