### ISSUE TITLE
Expect example of useAsyncFetchMore 

### ISSUE THREAD

**Issue by pig800509** [slorber/react-async-hook#40]
thanks

**Comment by slorber** [comment]
?

**Comment by pig800509** [comment]
@slorber I wonder call another useAsyncCallback by useAsyncCallback onSuccess result, and I saw there is useAsyncFetchMore in source code, so I expect example about it.

**Comment by slorber** [comment]
ah

this is an experiment I tried but it's likely to be removed in v2, as I decided that the lib's scope will remain the smallest possible, so I'm not going to document this as I don't want to encourage adoption of this extra api.
