### ISSUE TITLE
Explanation of "Handle race conditions"

### ISSUE THREAD

**Issue by k-funk** [slorber/react-async-hook#41]
Can you explain what this means in a short example? The race condition that I often come across is when I want to ignore all but the last request (most commonly used when a user is typing/autocompleting). This is how I solve it, but my project is littered with these `useRef`s an comparisons:

```
const [searchTerm, setSearchTerm] = useState('')
const currentSearch = useRef<string>()

useEffect(() => {
  // keep `searchTerm` so that if the response of a Api.doStuff() returns "out of order", we ignore the response, and keep waiting until the latest request
  currentSearch.current = searchTerm

  Api.doStuff().then(result => {
    if (currentSearch.current !== searchTerm) return
    ...
  }).catch(() => {
    if (currentSearch.current !== searchTerm) return
    ...
  }) 
}, [searchTerm])
```

Does the race condition that you handle solve this?

**Comment by slorber** [comment]
yes that's it

more details here: https://sebastienlorber.com/handling-api-request-race-conditions-in-react
