### ISSUE TITLE
Example page broken (CORS)

### ISSUE THREAD

**Issue by k-funk** [slorber/react-async-hook#42]
Getting this error in the js console of the [example page](https://react-async-hook.netlify.app/).

>Access to fetch at 'https://swapi.co/api/people/1/' from origin 'https://react-async-hook.netlify.app' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

However, it looks like the app isn't working at all:  `curl 'https://swapi.co/api/people/?search=z'`

**Comment by slorber** [comment]
yes, that's annoying but the API .co is offline now, and someone deployed a new one with .dev 

will update that soon

**Comment by slorber** [comment]
replaced by swapi.dev
