### ISSUE TITLE
Types don't allow synchronous return

### ISSUE THREAD

**Issue by trentmwillis** [slorber/react-async-hook#49]
We have a use case where, if a condition is met, then we need to execute an async function, but otherwise we can just return a static value.

Currently, the types for the library don't allow this as the function passed into `useAsync` must return a `Promise`: https://github.com/slorber/react-async-hook/blob/dddfc1c1b97ff8736b9237c50e2b35610c62ed75/src/index.ts#L304

However, I noticed when looking at the source that returning a non-`Promise` value is supported:

https://github.com/slorber/react-async-hook/blob/dddfc1c1b97ff8736b9237c50e2b35610c62ed75/src/index.ts#L272

So would it be possible to update the types for `useAsync` to be more lenient? Thanks in advance!

(P.S., we really like working with this library, makes dealing with async code much easier overall 😄)

**Comment by slorber** [comment]
Hey, thanks for the feedback

I'm not really willing to broaden that type because this library is primarily made for async callbacks. 

Even if we support synchronous callbacks at runtime, I think allowing it in `useAsync` could open the door to typos and bugs.
