### ISSUE TITLE
Passing object / arrays as params to useAsync

### ISSUE THREAD

**Issue by clementoriol** [slorber/react-async-hook#5]
Hi !
I’m enjoy using the library quite a lot, it simplifies a lot of the async stuff I’m doing.

However, there’s a use case I’ve got that currently causes an issue: 
On occasions, I have to make some request with a more complex payload than what your exemples shows. It could be objects, arrays, or even a mix of those.

Often when using these I’m constructing them on-the-fly, like this : 

```
const payload = buildPayloadFromState(state); // I’m a nested object
const stuff = useAsync(fetchStuff, [payload]);
```

**The issue :**
Since this library relies on `useEffect` and `useEffect` doesn’t perform deep comparison, if I pass objects or arrays as arguments to useAsync, they will be considered as changed even if they haven’t. This results in my fetch function begin constantly triggered.

[Example here](https://codesandbox.io/s/gracious-kowalevski-jp2t3)

*(edit, precisions)* I'm aware that I could find another way to pass the payload to my fetchStuff function (with a closure, or by building the fetch function from my component) but I actually want to retrigger my fetchStuff function if the payload has changed.

**What should happen :**
What I’m expecting is to be able to pass objects / arrays / nested objects as params to `useAsync`, and my fetch function to be triggered only when they have changed (using deep comparison, not reference comparison).

- Am I missing an obvious way of achieving this ? 
- If not, would you be open about adding a way to use deep comparison on the params ? I’m guessing it should be an option because it’s quite an expensive action, so you probably wouldn’t want to trigger it needlessly.

**Comment by slorber** [comment]
Hey @clementoriol :)

Already had this case




You can weither memoize your payload creation:

```
const payload = useMemo(() => buildPayloadFromState(state.a,state.b),[state.a,state.b]); 
const stuff = useAsync(fetchStuff, [payload]);
```

Or decide to execute the load manually with useAsyncCallback. Even if this is more suited for mutations, you can also control loading data with a callback but you'll have to decide yourself when to execute it

```
const stuff = useAsyncCallback(fetchStuff);
const loadStuff = () => {
  stuff.execute([state.a,state.b])
}
```

**Comment by clementoriol** [comment]
Hey @slorber :)
Thanks for your input 👍 

Ooh, good thinking on the memoized function, it does return the old new reference when nothing has changed !

Only thing is that there's [this warning on the react docs](https://reactjs.org/docs/hooks-reference.html#usememo) that kind of tells that it could be unsafe to rely on useMemo for this : 
```
You may rely on useMemo as a performance optimization, not as a semantic guarantee. In the future, React may choose to “forget” some previously memoized values and recalculate them on next render, e.g. to free memory for offscreen components. Write your code so that it still works without useMemo — and then add it to optimize performance.
```

But it does work.

I do like the useAsyncCallback option too, it can be used in association with the [use-deep-compare-effect](https://github.com/kentcdodds/use-deep-compare-effect) library to achieve exactly what I want: 

```
  const payload = buildPayloadFromState(items);
  const stuff = useAsyncCallback(fetchStuff);

  useDeepCompareEffect(() => {
    stuff.execute();
  }, [payload]);
```

Thanks 👍 💯

**Comment by slorber** [comment]
Ah yeah, that's true useMemo does not offer that guarantee.


Another option is to cherry pick all your needed dependencies into the dependency array. Note that the typing always allow to pass a no-arg async function as parameter even if the array has params, which gives some the freedom to choose on which param change a refetch is needed. 

```tsx
const stuff = useAsync(() => fetchStuff({a: state.a,b: state.b}), [state.a, state.b]);
```

Sometimes the refetch should only happen if a changes, not b:

```tsx
const stuff = useAsync(() => fetchStuff({a: state.a,b: state.b}), [state.a]);
```

Of course here a and b should be equal to former values and not new objects, otherwise using deep comparison is probably simpler to use. There's also probably already a hook somewhere that offers guarantees that useMemo does not.

**Comment by slorber** [comment]
improved the doc here: https://github.com/slorber/react-async-hook/blob/master/README.md#how-to-have-better-control-when-things-get-fetchedrefetched
