### ISSUE TITLE
Expose setError in useAsyncCallback

### ISSUE THREAD

**Issue by nandorojo** [slorber/react-async-hook#52]
I'd like to set the error from `useAsyncCallback`.

```js
const { setError, execute } = useAsyncCallback(() => ...)
```

The use case: a user submits a formik form. The backend returns specific fields that errored (such as using a duplicate username). In order to send these errors into the form, I need to "catch" the error on submit, and set them:

```jsx
const { execute, error } = useAsyncCallback(submitForm)

return (
  <Formik
    onSubmit={(submission, { setFieldError }) => {
      try {
        execute(submission)
        // this catch causes useAsyncCallback to miss the error
      } catch (e) {
        if (e.fieldErrors) {
          e.fieldErrors.forEach((fieldError) => setFieldError(fieldError.path, fieldError.message))
        }
      }
    }}
  />
)
```

I would like to call `setErrors` inside of the `catch` so that I can properly reflect the error in other parts of the screen:

```jsx
const { execute, error, setErrors } = useAsyncCallback(submitForm)

return (
  <>
    <ErrorNote error={error} />
    <Formik
      onSubmit={(submission, { setFieldError }) => {
        try {
          execute(submission)
          // this catch causes useAsyncCallback to miss the error
        } catch (e) {
          // I'd like to add this
          setErrors(e)
          if (e.fieldErrors) {
            e.fieldErrors.forEach((fieldError) => setFieldError(fieldError.path, fieldError.message))
          }
        }
      }}
    />
  </>
)
```

Thanks!

**Comment by nandorojo** [comment]
Current workaround:

```js
const { set, result, loading, status, ...callback } = useAsyncCallback(submitForm)

const setError = useCallback(
  (error: ServerError) => {
    set({
      error,
      result,
      loading,
      status
    })
  },
  [loading, result, set, status]
)
```
Is this right?

**Comment by slorber** [comment]
Hi,

If `execute()` fails, then the error is already set for you normally, you don't need to manually set it as any error thrown

I don't understand why `setErrors` and not `setError` btw, why do you want to set multiple errors in this lib? 

Also, there's already a `setErrors` fn being returned, and also `merge({error})` if you just want to update one state attribute.

Will try to document this better for v2 but unfortunately not much time to work on this lib currently

**Comment by nandorojo** [comment]
I don't see a setError in the types for useAsyncCallback.

The reason I need to catch it in the submit step is because I need access to Formik's `setFieldError` which comes from its context. 

Are you sure `useAsyncCallback` returns `merge` and `setErrors`? I see `set` but not `setErrors`

**Comment by slorber** [comment]
Just checked and `useAsyncCallback` returns merge / set, not setError (and setErrors doesn't even exist)

I'm not sure it's really required to provide a setError method, particularly when it can be done in userland and I'm now focusing on making this lib the smallest abstraction for data-fetching.

I'm extending the scope of `set()` to accept the functional form of setState (it already worked, but not in TS types)

You should now be able to do this more easily:

```js
const setError = useCallback(
  (error: ServerError) => set(state => ({...state, errror})),
  [set]
)
```
