### ISSUE TITLE
Missing info on reset

### ISSUE THREAD

**Issue by MartinMalinda** [slorber/react-async-hook#6]
I'm looking into the docs and I don't see any info on what's the recommended way to clean up, when using `useAsync` or `useAsyncCallback`.

Currently I'm using my own hooks that are simple wraps over `useEffect` and `useState`.

```js
  useEffect(() => {
    const ref = fireGet(path, data => {
      cb(data);
    });

    return () => {
      ref.off();
    };
  }, effectParams || [path]);
```

And I'm refactoring this to `react-async-hook` and I'm wondering where to put that function that turns off the WebSocket connection.

Looking into the code, there's an option to provide a  `reset`  callback. Is that what I need?

Thanks for any info and thanks for creating this lib!

**Comment by slorber** [comment]
Hi

Sorry but I'm not totally sure to understand what fireGet does. To me it does look like subscribing to some kind of stream (firebase?)

This library is mostly to handle single async results, not a stream of async data. But I could see how to support a stream/observable, this should not be too hard.

If I'm wrong and you expect a single result, and no update afterward, you can simply create a promise based interface to your method. If you need ability to cancel a pending request you can use the abort signal provided.

**Comment by MartinMalinda** [comment]
You're right. I'm using Firebase and I'm subscribing to data.

What I need in this scenario is:

1) start a subscription
2) enter loading state
3) turn off the loading state on first incoming data
4) keep the subscription open
5) turn the subscription off when the component is destroyed

I wondered if I could use the `useAsync`. Well, so far I'll stick with my own custom hook. I'm using `useAsync` where I'm dealing with single async results.

**Comment by slorber** [comment]
great :)

I'll see if it's worth adding support for observables / streams, but don't have time to work on this now

I've created a separate issue: https://github.com/slorber/react-async-hook/issues/7
