### ISSUE TITLE
Support observables / stream of result?

### ISSUE THREAD

**Issue by slorber** [slorber/react-async-hook#7]
See https://github.com/slorber/react-async-hook/issues/6

Should it be in this lib or in a separate lib? Isn't there a lib published that already does that?

**Comment by fabiosantoscode** [comment]
This looks like it does that job: https://github.com/LeetCode-OpenSource/rxjs-hooks

I don't suppose rxjs users would let hooks just pass by without writing cool libraries integrating them with rxjs :)

**Comment by slorber** [comment]
yes, that lib seems quite advanced for observables, it's probably not worth to support this here then :)
